const { app, BrowserWindow, screen } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { execFile } = require('node:child_process');
const output = path.join(__dirname, '..', 'build', 'desktop-smoke');
fs.mkdirSync(output, { recursive: true });
app.setPath('userData', path.join(output, 'profile'));
fs.rmSync(path.join(output, 'profile', 'ai.json'), { force: true });
// An isolated smoke run must not alter the user's Windows startup preference.
app.setLoginItemSettings = () => {};
require('../electron/main.cjs');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const errors = [];
app.on('web-contents-created', (_event, contents) => {
  contents.on('console-message', (_event, level, message) => { if (level === 3) errors.push(message); });
});
function native(action, target) {
  const args = ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', path.join(__dirname, '..', 'electron', 'window-control.ps1'), '-Action', action];
  if (target) args.push('-Handle', target.handle, '-OwnerProcess', String(target.process));
  return new Promise((resolve, reject) => execFile('powershell.exe', args, { windowsHide: true, timeout: 10000 }, (error, stdout) => {
    if (error) reject(error); else { try { resolve(JSON.parse(stdout.trim())); } catch (error) { reject(error); } }
  }));
}
app.whenReady().then(async () => {
  try {
    await delay(1600);
    const pet = BrowserWindow.getAllWindows().find(win => win.webContents.getURL().endsWith('desktop.html'));
    assert(pet, 'Desktop window exists');
    await pet.webContents.executeJavaScript('window.desktopPet.updateSettings({microActions:false,wander:false})');
    await delay(150);
    const rect = await pet.webContents.executeJavaScript('(() => {const r=document.querySelector("#petShell").getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()');
    pet.setIgnoreMouseEvents(false);
    pet.webContents.sendInputEvent({ type: 'mouseDown', ...rect, button: 'left', clickCount: 1 });
    pet.webContents.sendInputEvent({ type: 'mouseUp', ...rect, button: 'left', clickCount: 1 });
    await delay(500);
    assert.equal(await pet.webContents.executeJavaScript('document.body.dataset.state'), 'click', 'Click is not overwritten by a drop');
    const first = await pet.webContents.executeJavaScript('document.querySelector("#speechBubble").textContent');
    pet.webContents.send('pet:command', { type: 'interaction', action: 'chat' });
    await delay(650);
    const second = await pet.webContents.executeJavaScript('document.querySelector("#speechBubble").textContent');
    assert.notEqual(first, second, 'Chat does not repeat immediately');
    pet.webContents.send('pet:command', { type: 'interaction', action: 'rps:0' });
    await delay(800);
    assert.match(await pet.webContents.executeJavaScript('document.querySelector("#speechBubble").textContent'), /^我出/);
    fs.writeFileSync(path.join(output, 'pet.png'), (await pet.webContents.capturePage()).toPNG());
    await pet.webContents.executeJavaScript('window.desktopPet.openAIChat()');
    await delay(600);
    const settings = BrowserWindow.getAllWindows().find(win => win.webContents.getURL().endsWith('settings.html'));
    assert(settings);
    await settings.webContents.executeJavaScript('document.querySelector("#aiPersona").value="长人格测试。".repeat(500); document.querySelector("#aiPersona").dispatchEvent(new Event("input")); document.querySelector("#personaForm").requestSubmit()');
    await delay(200);
    assert.equal((await settings.webContents.executeJavaScript('window.desktopPet.getAIConfig()')).persona.length, 3000);
    assert.match(await settings.webContents.executeJavaScript('document.querySelector("#personaCount").textContent'), /3000 \/ 20000/);
    await settings.webContents.executeJavaScript('document.querySelector("#aiPersona").value="字".repeat(20001); document.querySelector("#aiPersona").dispatchEvent(new Event("input"))');
    assert.equal(await settings.webContents.executeJavaScript('document.querySelector("#aiPersona").checkValidity()'), false);
    assert.equal(await settings.webContents.executeJavaScript('document.querySelector("#aiPersona").value.length'), 20001, 'Over-limit paste is not silently truncated');
    await settings.webContents.executeJavaScript('document.querySelector("#aiPersona").value="叫我队长，温柔且简短。"; document.querySelector("#aiPersona").dispatchEvent(new Event("input"))');
    await settings.webContents.executeJavaScript('document.querySelector("#aiPersona").value="叫我队长，温柔且简短。"; document.querySelector("#personaForm").requestSubmit()');
    await delay(200);
    assert.equal((await settings.webContents.executeJavaScript('window.desktopPet.getAIConfig()')).persona, '叫我队长，温柔且简短。');
    assert(!fs.existsSync(path.join(output, 'profile', 'ai.json')), 'Saving personality does not create API configuration');
    await settings.webContents.executeJavaScript('document.querySelector("#personaForm").scrollIntoView()');
    await delay(150);
    fs.writeFileSync(path.join(output, 'persona.png'), (await settings.webContents.capturePage()).toPNG());
    await settings.webContents.executeJavaScript('document.querySelector("#resetPersona").click()');
    await delay(150);
    const personaConfig = await settings.webContents.executeJavaScript('window.desktopPet.getAIConfig()');
    assert.equal(personaConfig.persona, personaConfig.defaultPersona);
    assert.equal(await settings.webContents.executeJavaScript('document.querySelector("#scale").value'), '1');
    fs.writeFileSync(path.join(output, 'settings.png'), (await settings.webContents.capturePage()).toPNG());
    const http = require('node:http');
    let aiRequests = 0;
    const server = http.createServer((request, response) => {
      let body = '';
      request.on('data', chunk => { body += chunk; });
      request.on('end', () => {
        aiRequests++;
        const data = JSON.parse(body);
        assert.equal(request.url, '/v1/chat/completions');
        assert.equal(data.model, 'smoke-model');
        assert.equal(request.headers.authorization, 'Bearer smoke-key');
        response.setHeader('Content-Type', 'application/json');
        response.end(JSON.stringify({ choices: [{ message: { content: '你好，我在这里。今天过得怎么样？' } }] }));
      });
    });
    await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
    const aiConfig = { enabled: true, baseUrl: `http://127.0.0.1:${server.address().port}/v1`, model: 'smoke-model', apiKey: 'smoke-key' };
    await settings.webContents.executeJavaScript(`(() => {
      const config = ${JSON.stringify(aiConfig)};
      document.querySelector('#aiBaseUrl').value = config.baseUrl;
      document.querySelector('#aiModel').value = config.model;
      document.querySelector('#aiKey').value = config.apiKey;
      document.querySelector('#aiConfigForm').requestSubmit();
    })()`);
    await delay(200);
    await settings.webContents.executeJavaScript('document.querySelector("#aiEnabled").click()');
    await delay(200);
    const configured = await settings.webContents.executeJavaScript('window.desktopPet.getAIConfig()');
    assert.equal(configured.enabled, true);
    assert(!JSON.stringify(configured).includes('smoke-key'));
    await pet.webContents.executeJavaScript('document.querySelector("#petShell").click()');
    await delay(500);
    const chat = BrowserWindow.getAllWindows().find(win => win.webContents.getURL().endsWith('chat.html'));
    assert(chat, 'Click with AI enabled opens the desktop chat');
    await chat.webContents.executeJavaScript('document.querySelector("#chatInput").value="你好"; document.querySelector("#chatForm").requestSubmit()');
    await delay(700);
    assert.equal(aiRequests, 1);
    assert.match(await chat.webContents.executeJavaScript('document.querySelector("#messages").textContent'), /今天过得怎么样/);
    fs.writeFileSync(path.join(output, 'chat.png'), (await chat.webContents.capturePage()).toPNG());
    await settings.webContents.executeJavaScript('document.querySelector("#aiDetails").open=true; document.querySelector("#aiSection").scrollIntoView()');
    await delay(200);
    fs.writeFileSync(path.join(output, 'ai-settings.png'), (await settings.webContents.capturePage()).toPNG());
    await settings.webContents.executeJavaScript('document.querySelector("#aiEnabled").click()');
    await delay(200);
    assert.equal((await chat.webContents.executeJavaScript('window.desktopPet.sendAIMessage("关闭后不发送")')).ok, false);
    assert.equal(aiRequests, 1);
    await pet.webContents.executeJavaScript('document.querySelector("#petShell").click()');
    assert.equal(await pet.webContents.executeJavaScript('document.body.dataset.state'), 'click');
    chat.close();
    server.close();
    const targetWindow = new BrowserWindow({ width: 500, height: 400, title: 'Pet smoke target', show: true });
    await targetWindow.loadURL('data:text/html,<title>Pet smoke target</title><h1>Window control smoke test</h1>');
    const target = (await native('list')).find(item => item.title === 'Pet smoke target');
    assert(target, 'Native helper lists the test window');
    const area = screen.getDisplayMatching(targetWindow.getBounds()).workArea;
    await native('left', target);
    assert.equal(targetWindow.getBounds().x, area.x);
    assert.equal(targetWindow.getBounds().width, Math.floor(area.width / 2));
    await native('right', target);
    assert.equal(targetWindow.getBounds().x, area.x + Math.floor(area.width / 2));
    await native('minimize', target);
    assert(targetWindow.isMinimized());
    await native('restore', target);
    assert(!targetWindow.isMinimized());
    await assert.rejects(native('minimize', { ...target, process: 0 }), 'Reject stale/invalid window owner');
    assert.deepEqual(errors, []);
    console.log('PASS: desktop interaction, AI chat with local mock, disabled AI sends nothing, encrypted key, settings, native window control');
    app.exit(0);
  } catch (error) { console.error(error); app.exit(1); }
});

